### ISSUE TITLE
Improve the See All Sponsors block implementation

### ISSUE THREAD

**Issue by leolandotan** [promet/drupalcampcebu2015#116]
## Desired output
![see-all-sponsors-or-propose-a-session](https://cloud.githubusercontent.com/assets/3686017/10657255/047c25e4-78bb-11e5-8cc8-d5eb372147d2.jpeg)

## Requirements
* Original text should be "See All Sponsors"
* Transformed to uppercase
* Should link to http://drupalcampcebu2015.dev/sponsors
* Should be shown in all pages except for the http://drupalcampcebu2015.dev/sponsors
* Follow the colors. You can match from existing styles already.

## Current implementation and issue
* Hard coded in the page.html.twig file
* Hidden through CSS.
* Has theme issue on mobile screens.
![dc15-see-all-sponsors-tab](https://cloud.githubusercontent.com/assets/3686017/10657310/f246e304-78bb-11e5-8daf-d9eaa1880d87.png)

### Option 1
* Use the hard coded implementation
* Maybe lessen the markup used
* Fix theme issue on mobile screens.

### Option 2
* Create a block, assign to the region and specify it's page visibility through the *Block Visibility* settings.
* Add the CSS class if you like by overriding the block.html.twig
* Remove the CSS rule that hide's the component for a specific page since were using *Block Visibility*.

**IMPORTANT** This needs to be discussed on Friday Oct 23, 2015 during the Hackathon.

**Comment by marychris** [comment]
Issue is fixed.
Fix included in PR https://github.com/promet/drupalcampcebu2015/pull/126
Option 1 was used.
