### ISSUE TITLE
Remove declared logo height

### ISSUE THREAD

**Issue by leolandotan** [promet/drupalcampcebu2015#117]
## Current implementation and issue
The logo is styled with ```height: 30em``` which up-scales the image and distorts it.

## Proposed solution
Remove the height since the image is quite big and not far from the 30em height.

**IMPORTANT** This needs to be discussed on Friday Oct 23, 2015 during the Hackathon.

**Comment by leolandotan** [comment]
Created a fix for this on PR #129.

**Comment by Luukyb** [comment]
Thanks !
