### ISSUE TITLE
Wysiwyg on page content type

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#119]
Simple Wysiwyg.
Images upload would be a plus.
Only on page content type.

**Comment by ascie** [comment]
Configure Text formats and editors Full HTML and set CKEditor as the default text editor. For the image uploads, just enable the image uploads option for it to show up as an IMCE function on the WYSIWYG module.

The WYSIWYG interface however is disabled with the current theme. The rest of the themes have this enabled including the base theme Classy which suggests that there may be some changes in the theme that has affected this functionality.

**Comment by Luukyb** [comment]
+1 for @ascie. We were missing the js inclusion on the theme template:
<js-bottom-placeholder token="{{ placeholder_token|raw }}">

**Comment by Luukyb** [comment]
JS inclusion file issue.
Seems like the dev site is not able to load the JS file since we changed the libraries loading on this ticket.

**Comment by Luukyb** [comment]
I had to disable the wysiwyg. It need to use jquery from the libraries. But the carousel can not use it yet.

JS Error : 
Uncaught TypeError: Cannot set property 'flexslider' of undefined

## How to reproduce ?

* In libraries file add : 
```yml
  js:
    public/js/flexslider/drupalcampcebu2015.flexslider.js: {}
  dependencies:
    - drupalcampcebu2015/boostrap
    - drupalcampcebu2015/flexslider
```
* In html.html.twig, remove : 
```
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="/themes/custom/drupalcampcebu2015/lib/flexslider/jquery.flexslider.js"></script>
    <script type="text/javascript" src="/themes/custom/drupalcampcebu2015/public/js/flexslider/drupalcampcebu2015.flexslider.js"></script>
```

**Comment by Luukyb** [comment]
JS is fixed.

We can now re-enable the wysiwyg and add support for images (needs to be tested).

Old text format disappeared, you will have to create a new one :  admin/config/content/formats/add

**Comment by marychris** [comment]
PR https://github.com/promet/drupalcampcebu2015/pull/168 merged by @Luukyb hence closing this issue.
