### ISSUE TITLE
Add UP Logo bellow the menu

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#121]
We need to add UP Logo bellow the menu.
You can find their logo online.

Since we need this to be on every server, I would recommend we include it directly on theme's template, rather than on a block.

**Comment by leolandotan** [comment]
### Additional Information
Based from the official website of the University of the Philippines http://www.up.edu.ph/about-up/the-university-seal/ and a [simple search](https://www.google.com/search?q=university+of+the+philippines+logo&tbm=isch&imgil=wgHTBQ1lueWkhM%253A%253BwsUkldlBZQtbGM%253Bhttps%25253A%25252F%25252Fen.wikipedia.org%25252Fwiki%25252FUniversity_of_the_Philippines&source=iu&pf=m&fir=wgHTBQ1lueWkhM%253A%252CwsUkldlBZQtbGM%252C_&biw=1069&bih=597&usg=__QQOKp1KNdgmEC5vrXPA7Ri21c4E%3D&ved=0CDYQyjdqFQoTCPqkxovc28gCFUqUlAodDnsMoA&ei=eMsrVvqIB8qo0gSO9rGACg#imgrc=wgHTBQ1lueWkhM%3A&usg=__QQOKp1KNdgmEC5vrXPA7Ri21c4E%3D) I think we can use [this logo](https://upload.wikimedia.org/wikipedia/en/e/e9/Unibersidad_ng_Pilipinas.png).

### Discussion
There was also a discussion that we would just use blocks for this and use a "Basic HTML" filter with Ckeditor enabled to add the image and would be more flexible to manage.

If this will be the option we will go for then this tasks would need to be done by two people. One would be to setup and export a new Text Format and the second would be the one to add the dynamic content on the live site.

What are your thoughts on this @Luukyb ?
