### ISSUE TITLE
Add drupal association link for membership

### ISSUE THREAD

**Issue by marychris** [promet/drupalcampcebu2015#123]
Image is https://assoc.drupal.org/files/Membership_drive_2015_180x150_1_0.png
This should be inserted in the footer.
![screen shot 2015-10-23 at 11 54 03 am](https://cloud.githubusercontent.com/assets/8597102/10684170/caa839c6-797c-11e5-8a63-e3a0eb1e4fc6.png)

This is the link; https://assoc.drupal.org/help-grow-our-membership

**Comment by Luukyb** [comment]
The capture is just a guideline, please add some space bellow the image and the text ;)
Make it look good :dancer:
