### ISSUE TITLE
Menu does not display more than 3 items

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#130]
The menu works with more than 3 items, but they are hidden by the font color (white).
Color of the font should be blue.
https://2015.drupalcebu.org/code-sprint

**Comment by leolandotan** [comment]
### Additional Information
This is what needs to be fixed if you don't notice anything wrong with the said page.

![dc15-130](https://cloud.githubusercontent.com/assets/3686017/10711969/55eeca4e-7abe-11e5-8e77-b2d98b17a797.png)

**Comment by marychris** [comment]
Fix been made at closed PR > https://github.com/promet/drupalcampcebu2015/pull/169. Closing this issue @Luukyb .
