### ISSUE TITLE
Images on Wysiwyg

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#146]
We currently have the Wysiwyg, but it doesn't support images, due to a JS error (from flexslider).
JS should be loaded using the librairies file, not on the template.

  # js:
  #   public/js/flexslider/drupalcampcebu2015.flexslider.js: {}
  # dependencies:
  #   - drupalcampcebu2015/boostrap
  #   - drupalcampcebu2015/flexslider
  #   - core/jquery
  #   - core/jquery.once

Best would be to load flexslider using hook_element_info_alter(), see https://www.drupal.org/node/2274843

**Comment by Luukyb** [comment]
JS is fixed.

We can now re-enable the wysiwyg and add support for images (needs to be tested).

**Comment by Luukyb** [comment]
Old text format disappeared, you will have to create a new one :  admin/config/content/formats/add

**Comment by Luukyb** [comment]
Do https://github.com/promet/drupalcampcebu2015/issues/119 first

**Comment by Luukyb** [comment]
Images to be added on the text format called "CKEditor Full HTML"

**Comment by marychris** [comment]
Default directory is inline images, But image is not uploading with 'cannot find directory' report on log message. Checked inline-images directory on sublime and image is uploaded yet drupal can't seem to see it. So left upload directory blank, image is uploaded. Images uploaded is then automatically stored at /sites/default/files
@Luukyb
