### ISSUE TITLE
Close proposals

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#155]
Remove the permission for authenticated users to post proposals.
Make sure that everything that leads to submit a proposal is removed.
Review the site as authenticated (but not admin) and make sure no you are led to submit a proposal.

**Comment by marychris** [comment]
PR merged by @Luukyb . Will close this issue.

**Comment by Luukyb** [comment]
Please update the proposal view to not use the menu. thanks

**Comment by donnabel** [comment]
We should change the Proposal Intro in the homepage and remove the session proposal block since it is already closed and the link is redirecting to an Access Denied page.

**Comment by marychris** [comment]
It's done @donnabel :) changes are in the pending PR #163

**Comment by Luukyb** [comment]
Pending, we need to approve the sessions on prod first.

**Comment by marychris** [comment]
Sessions on prod had been approved. Closing this issue @Luukyb .
