### ISSUE TITLE
New fields on user profile needs to be styled

### ISSUE THREAD

**Issue by marychris** [promet/drupalcampcebu2015#162]
![screen shot 2015-10-28 at 4 00 21 pm](https://cloud.githubusercontent.com/assets/8597102/10782676/41bdb310-7d8d-11e5-8ec9-4efecb720262.png)

**Comment by Luukyb** [comment]
Not styled. Hidden.

**Comment by marychris** [comment]
We have four new fields, I believe the two fields, company and role won't be hidden? Or will they?
@Luukyb

**Comment by Luukyb** [comment]
News fields:

**Comment by marychris** [comment]
Styling of these fields will be referenced to https://github.com/promet/drupalcampcebu2015/issues/135
@leolandotan  @Luukyb

**Comment by marychris** [comment]
This issue is fixed https://github.com/promet/drupalcampcebu2015/pull/173 @Luukyb
