### ISSUE TITLE
Links for sponsor websites

### ISSUE THREAD

**Issue by donnabel** [promet/drupalcampcebu2015#165]
This is to add links to sponsors' websites in the sponsorship block. Since it seems that we cannot add links for the images this is the proposed solution: https://s3.amazonaws.com/uploads.hipchat.com/144376/1612423/1HjMfyFCRJdY3UT/sponsors-list.jpg

**Comment by marychris** [comment]
PR #166 made.

**Comment by Luukyb** [comment]
Here is the link for the last sponsor ANNAI https://www.drupal.org/node/2466689

**Comment by Luukyb** [comment]
Promet : https://www.prometsource.com
Pantheon : https://pantheon.io
