### ISSUE TITLE
Margin for p tag

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#178]
Margin was assigned to 0 for session page, like 
.content p, .view-content p {
    margin: 0;
}

This change should not affect the other pages. Please make the margin to 0 specific for the session's page p tag.

In brief :
This page needs margin : https://2015.drupalcebu.org/venue
![screenshot 2015-11-02 11 30 53](https://cloud.githubusercontent.com/assets/1465207/10873836/4cb0a04a-8155-11e5-8026-786f43831edf.png)

This page doesn't need margin : https://2015.drupalcebu.org/sessions
![screenshot 2015-11-02 11 31 05](https://cloud.githubusercontent.com/assets/1465207/10873839/5b0549b6-8155-11e5-890b-1ec66f663e8c.png)

**Comment by marychris** [comment]
Fix been made at closed PR https://github.com/promet/drupalcampcebu2015/pull/179. Closing this issue @Luukyb .
