### ISSUE TITLE
Footer needs some love

### ISSUE THREAD

**Issue by Luukyb** [promet/drupalcampcebu2015#203]
I did a quick re-design of the footer. :santa: 

![footer-redesign](https://cloud.githubusercontent.com/assets/1465207/10960823/bf77bf04-83c2-11e5-9289-82f8e91c89f6.png)

D8 logo https://www.drupal.org/files/drupal%208%20logo%20isolated%20CMYK%2072.png

**Comment by marychris** [comment]
Then let's give it some loving

**Comment by Luukyb** [comment]
Thanks @marychris !
